import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#1e100d",
        "inverse-on-surface": "#3e2c29",
        "surface-tint": "#ffb4a7",
        "surface-bright": "#483531",
        "on-error-container": "#ffdad6",
        "on-background": "#fadcd7",
        "tertiary-container": "#3499d3",
        error: "#ffb4ab",
        "on-surface-variant": "#e4beb7",
        "primary-fixed": "#ffdad4",
        "surface-container-low": "#271815",
        "secondary-container": "#5c451e",
        "on-tertiary": "#00344e",
        "on-error": "#690005",
        "inverse-primary": "#b91e0d",
        "on-surface": "#fadcd7",
        "surface-container-high": "#372623",
        "on-tertiary-container": "#002d44",
        primary: "#ffb4a7",
        "secondary-fixed": "#ffdeac",
        "primary-container": "#ff553d",
        "primary-fixed-dim": "#ffb4a7",
        "on-primary": "#670400",
        "on-secondary-fixed-variant": "#59431c",
        background: "#1e100d",
        "tertiary-fixed": "#c9e6ff",
        "on-tertiary-fixed": "#001e2f",
        "tertiary-fixed-dim": "#8aceff",
        tertiary: "#8aceff",
        "error-container": "#93000a",
        "surface-dim": "#1e100d",
        "on-secondary-container": "#d4b483",
        "on-primary-container": "#5b0300",
        "surface-container": "#2c1c19",
        outline: "#ab8983",
        "outline-variant": "#5b403b",
        secondary: "#e3c290",
        "on-tertiary-fixed-variant": "#004b6f",
        "on-secondary": "#412d07",
        "on-primary-fixed": "#400200",
        "surface-container-highest": "#43302d",
        "surface-container-lowest": "#180a08",
        "inverse-surface": "#fadcd7",
        "surface-variant": "#43302d",
        "secondary-fixed-dim": "#e3c290",
        tomato: "#E23D28",
        gold: "#D4B483",
        "level-0": "#0E1114",
        "level-1": "#161B20",
        "level-2": "#1C232A",
        "on-tomato": "#F4F1EA",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        lg: "40px",
        md: "24px",
        sm: "12px",
        xs: "4px",
        "margin-desktop": "64px",
        base: "8px",
        gutter: "20px",
      },
      fontFamily: {
        newsreader: ["var(--font-newsreader)", "Georgia", "serif"],
        geist: ["var(--font-geist)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md-mobile": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-lg": ["22px", { lineHeight: "28px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
